# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='twit',
            name='posted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='twit',
            name='updated_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
